[build-system]
requires = ["mesonpep517 @ https://gitlab.com/thiblahute/mesonpep517/-/archive/master/mesonpep517-master.zip"]
# requires = ["mesonpep517"]
build-backend = "mesonpep517.buildapi"

#[tool.mesonpep517.metadata]

[project]
version = "20220121"
dependencies = ["pyyaml"]
requires-python = ">=3.6"

[project.scripts]
xgrow = "xgrow._script_xgrow:main"
